console.log('4' + '3'); // o operador ' + ' entre strings concatena e entre numeros ele soma ...
//
console.log('4' + 3); // ele transforma o tipo number para string, a string se sobressai e o numero continua sendo string ...
//
console.log('4' * '3'); // multiplicaçao de strings nao tem efeito nenhum, o javascript nao sabe multiplicar string => devida a isso ele transforma o valor da string em numeros ....
//
console.log(Number(''));  console.log(Number(' ')); // strings vazias e espaços em branco resultam em 0 seu valro// strings vazias e espaços em branco resultam em 0 seu valor ...
//
console.log(Boolean(1)); // resultado sera true ...
console.log(Boolean(0)); // resultado sera false ... quando tem 0 
console.log(Boolean('')); // resultado sera false ... string vazia
console.log(Boolean('a')); // resultado sera true ...
// resumindo: uma string no booleano vazia retorna true, numa de valor 0 retorna false, numa de valor string vazia retorna false, numa de valor com caracteres retorna true...
